#
# CSE183 Assignment 7
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 7
  version: 0.1.0
  title: CSE183 Assignment 7

servers:
  - url: http://localhost:3010

paths:
  /v0/mail:
    get:
      description: Returns all EMail
      parameters:
      - name: mailbox
        in: query
        description: Name of mailbox
        required: false
        schema:
          type: string
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailsResponse'
        404:
          description: Mailbox not found

        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new email
      requestBody:
        description: Email to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEmail'
      responses:
        201:
          description: Application response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        400:
          description: Unexpected properties
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v0/mail/{id}:
    get:
      description: Returns one EMail
      parameters:
      - name: id
        in: path
        description: Email id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        404:
          description: Mailbox not found

        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Moves one EMail
      parameters:
      - name: id
        in: path
        description: Email id
        required: true
        schema:
          type: string
      - name: mailbox
        in: query
        description: Name of Mailbox
        required: true
        schema:
          type: string
      responses:
        204:
          description: Success
        404:
          description: id does not identify a known email
        409:
          description: Cannot move non-sent mail to sent mailbox
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    EmailsResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          mail:
            type: array
            items:
              $ref: '#/components/schemas/Email'

    Email:
      type: object
      properties:
        id:
          type: string
        to-name:
          type: string
        to-email:
          type: string
        subject:
          type: string
        received:
          type: string
        content:
          type: string
        from-name:
          type: string
        from-email:
          type: string

      required:
        - id
        - to-name
        - to-email
        - subject
        - received
        - from-name
        - from-email

    NewEmail:
      type: object
      properties:
        to-name:
          type: string
        to-email:
          type: string
        subject:
          type: string
        received:
          type: string
        content:
          type: string

      required:
        - to-name
        - to-email
        - received
